# Generated by Django 6.1.1 on 2026-10-04 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUED', 'QUEUED'), ('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('BLOCKED', 'BLOCKED')], default='QUEUED', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('replay_status_code', models.IntegerField(blank=True, null=True)),
                ('replay_response_body', models.JSONField(blank=True, default=dict)),
                ('replay_latency_ms', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captured_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replays', to='capture.capturedrequest')),
            ],
            options={
                'db_table': 'replay',
                'constraints': [models.UniqueConstraint(fields=('captured_request', 'idempotency_key'), name='unique_replay_idempotency')],
            },
        ),
    ]
