# Generated by Django 6.1.1 on 2026-10-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_key', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('api_key_hash', models.CharField(blank=True, default='', max_length=128, unique=True)),
                ('target_base_url', models.URLField(default='http://localhost:8001')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
