# Generated by Django 6.1.1 on 2026-10-04 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('method', models.CharField(max_length=12)),
                ('path', models.CharField(max_length=500)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('request_body', models.JSONField(blank=True, default=dict)),
                ('response_status', models.IntegerField(default=0)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('body_truncated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captured_requests', to='projects.project')),
            ],
            options={
                'db_table': 'captured_request',
                'indexes': [models.Index(fields=['project', 'created_at'], name='captured_re_project_5c319b_idx'), models.Index(fields=['project', 'response_status'], name='captured_re_project_7687f2_idx'), models.Index(fields=['project', 'method'], name='captured_re_project_4ad5c0_idx'), models.Index(fields=['request_id'], name='captured_re_request_baa19f_idx')],
            },
        ),
    ]
